### ISSUE TITLE
Sorry, I honestly wasn't aware of the act, I deleted everything that was linked to the site and the programmer. Thanks for helping me and I'm sorry for what happened.

### ISSUE THREAD

**Issue by ghost** [Skykai521/AndroidDeveloperAdvancedManual#3]
Sorry, I honestly wasn't aware of the act, I deleted everything that was linked to the site and the programmer. Thanks for helping me and I'm sorry for what happened.

**Comment by Skykai521** [comment]
Sorry, I don't understand what you're talking about
